packages:
  - apps/*
  - packages/*
  - ../emdash-plugin-code-block-pro

allowBuilds:
  better-sqlite3: false
  esbuild: true
  sharp: false
  workerd: true

blockExoticSubdeps: true

minimumReleaseAge: 1440

minimumReleaseAgeExclude:
  - emdash
  - '@emdash-cms/*'

patchedDependencies:
  '@emdash-cms/admin': patches/@emdash-cms__admin.patch
